### ISSUE TITLE
Firefox bugs

### ISSUE THREAD

**Issue by ianschuler** [satsummit/landscape#35] opened 2015-12-17 17:02 UTC
I noticed a few bugs in firefox, latest version (43.0)

- Can't scroll past header. The page keeps resetting to the top of the page.
- Imagery switcher buttons stack.

![](https://www.evernote.com/l/ACOC7cwho_ZBMKXD9VU6hjs2jhRtRmcl318B/image.png)

**Comment by smit1678** [comment] 2016-02-22 12:38
Looked into the scrolling issue briefly. Looks like if you can scroll down the page far enough where the sticky nav kicks in, then you can finish scrolling the page and it does not reset to the top. Seems like the issue is may be with the sticky nav. 

cc @nbumbarger

**Comment by nbumbarger** [comment] 2016-02-22 17:50
should be fixed in https://github.com/satsummit/landscape/pull/42

**Comment by smit1678** [comment] 2016-02-29 11:31
Tested and looks good. Closing.

**Closed by smit1678** 2016-02-29 11:31 UTC
